VeryGoodOpenSource/very_good_analysis

- README.md
- docs: add vgv branding to README
> docs: add vgv branding to README

- CHANGELOG.md
- lib/very_good_analysis.dart
- pubspec.yaml
- chore: v1.0.1
- docs: README improvements
> chore: v1.0.1

- README.md
- docs: minor updates to README
> docs: minor updates to README

- lib/analysis_options.1.0.0.yaml
The package `test_coverage` creates a hidden file that should not be tracked by any tool. Adding it here on purpose will save use some setup time and configuration in the projects that used `very_good_analysis`.
> feat: added test/.test_coverage.dart to the list of ignored files

- CHANGELOG.md
- pubspec.yaml
> chore: v1.0.2

- lib/analysis_options.1.0.0.yaml
- lib/analysis_options.1.0.1.yaml
- lib/analysis_options.yaml
- Add new lints
`avoid_print `- Avoid print calls in production code.
`avoid_unnecessary_containers`
`prefer_final_in_for_each` - Prefer final in for-each loop variable if reference is not reassigned.
`prefer_final_locals` - Prefer final for variable declarations if they are not reassigned.
`prefer_const_declarations` - Prefer const over final for declarations.
`sized_box_for_whitespace`
> feat: add new lints

- CHANGELOG.md
- pubspec.yaml
> chore: v1.0.3

- CHANGELOG.md
- README.md
- pubspec.yaml
- docs: update documentation to reflect org update
> docs: update documentation to reflect org update

- .github/workflows/main.yaml
- CHANGELOG.md
- example/pubspec.yaml
- pubspec.yaml
Migrated code to null safety. Followed guide at https://dart.dev/null-safety/migration-guide
> chore: migrate to null safety

- CHANGELOG.md
- README.md
- pubspec.yaml
- docs: minor documentation and package description updates
> docs: minor documentation and package description updates

- .github/workflows/main.yaml
> ci: verify pub score

- lib/very_good_analysis.dart
- pubspec.yaml
- refactor: remove deprecated pedantic dependency (related to https://github.com/google/pedantic/pull/87)
> refactor: remove deprecated pedantic dependency

- CHANGELOG.md
- README.md
- pubspec.yaml
> chore: v2.1.2

- .github/workflows/main.yaml
- ci: use very_good_workflows for pana
> ci: use very_good_workflows for pana

- README.md
- pubspec.yaml
> chore: v4.0.0+1

- CHANGELOG.md
chore: update changelog for v5
> chore: update changelog for v5

- README.md
> docs: update `README`  for v5

- CHANGELOG.md
- README.md
- pubspec.yaml
> chore: v5.0.0+1

- CONTRIBUTING.md
> docs: add release docs

- CHANGELOG.md
- pubspec.yaml
**READY**
Related to #99
Prepares VGA pre-release.
> chore: v6.0.0-dev.1

- CHANGELOG.md
- pubspec.yaml
**READY**
Prepares v6.0.0 release.
> chore: v6.0.0

- README.md
**READY**
Updates README to point to 6.0.0
> docs: update readme to reference latest version

- .github/workflows/pub_publish.yaml
**READY**
Adding Github action to deploy to Pub
> chore: add github action for pub publish

- lib/analysis_options.7.0.0.yaml
> feat: add `avoid_catches_without_on_clauses`

- lib/analysis_options.7.0.0.yaml
> feat: add `document_ignores`

- .github/workflows/tool_linter_rules.yaml
- lib/very_good_analysis.dart
- tool/linter_rules/README.md
- tool/linter_rules/bin/inspect.dart
- tool/linter_rules/lib/linter_rules.dart
- tool/linter_rules/lib/src/models/linter_rule.dart
- tool/linter_rules/lib/src/models/models.dart
- tool/linter_rules/pubspec.yaml
- tool/linter_rules/test/src/models/fixtures/all_linter_rules.dart
- tool/linter_rules/test/src/models/linter_rule_test.dart
**READY FOR REVIEW**
Related to #120
> feat: allow checking for deprecated rules

- CHANGELOG.md
- pubspec.yaml
> chore: release 9.0.0-rc.1

- lib/analysis_options.10.0.0.yaml
- pubspec.yaml
**READY**
Removes `diagnostic_describe_all_properties` from `analysis_options.10.0.0.yaml`.
> chore: remove `diagnostic_describe_all_properties`
